# Generated by Django 4.1.2 on 2022-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0002_pacientes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacientes",
            name="obra_social",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pacientes",
            name="turno",
            field=models.BooleanField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pacientes", name="dni", field=models.IntegerField(),
        ),
    ]
