# Generated by Django 4.1.2 on 2022-11-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0005_pacientes_obra_social_alter_pacientes_telefono"),
    ]

    operations = [
        migrations.RemoveField(model_name="pacientes", name="turno",),
    ]
