# Generated by Django 4.1.2 on 2022-11-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0006_remove_pacientes_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctores",
            name="consultorio",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctores",
            name="especialidad",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="turnos",
            name="consultorio",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctores", name="dni", field=models.IntegerField(),
        ),
    ]
