# Generated by Django 4.1.2 on 2022-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0008_delete_doctores_delete_turnos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacientes", name="dni", field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="pacientes",
            name="telefono",
            field=models.CharField(max_length=10),
        ),
    ]
