# Generated by Django 4.1.2 on 2022-11-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0009_alter_pacientes_dni_alter_pacientes_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellido", models.CharField(max_length=20)),
                ("dni", models.CharField(max_length=8)),
                ("especialidad", models.CharField(max_length=20)),
                ("consultorio", models.CharField(max_length=20)),
            ],
        ),
    ]
