# Generated by Django 4.1.2 on 2022-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0010_doctores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turnos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=20)),
                ("paciente", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TurnosFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consultorio", models.CharField(max_length=20)),
            ],
        ),
    ]
