# Generated by Django 4.1.2 on 2022-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicaapp", "0011_turnos_turnosformulario"),
    ]

    operations = [
        migrations.DeleteModel(name="TurnosFormulario",),
        migrations.AddField(
            model_name="turnos",
            name="consultorio",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="turnos",
            name="fecha",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="turnos",
            name="horario",
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
